### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chung1912** [AmoyLab/Unla#162]
### ⚠️ 验证

- [x] 我已经搜索过 [issues](https://github.com/amoylab/unla/issues)，确信这不是一个重复的问题。

### Go 版本

1.21.0

### Unla 版本

v0.8.0

### Platform

Linux

### 📝 Bug 描述

Streamable HTTP对接时，客户端如果闲置一段时间，就不能连接了，调用的时候会提示如下错误：

`Error: Error: Error POSTing to endpoint (HTTP 400): {"jsonrpc":"2.0","id":2,"error":{"code":-32600,"message":"Invalid Request: Session not found"}}`

这时候客户端需要手动禁用mcp，然后再重新连接才可以，这个是客户端的问题还是Unla的问题？如果是Unla的问题希望可以解决

### 🔄 复现步骤

同上

### ✅ 预期行为

希望保持连接正常

### ❌ 实际行为

同上

**Comment by iFurySt** [comment]
用内存还是redis存放session？
```
# Session storage configuration
session:
  type: "${SESSION_STORAGE_TYPE:memory}"  # memory or redis
  redis:
    addr: "${SESSION_REDIS_ADDR:localhost:6379}"
    username: "${SESSION_REDIS_USERNAME:default}"
    password: "${SESSION_REDIS_PASSWORD:}"
    db: ${SESSION_REDIS_DB:0}
    topic: "${SESSION_REDIS_TOPIC:mcp-gateway:session}"
    prefix: "${SESSION_REDIS_PREFIX:session}"
    ttl: "${SESSION_REDIS_TTL:24h}"  # Session TTL in Redis
```

内存的话重启后就会丢失，如果使用redis的话，按照实际情况配置一下TTL
